window.KZN_PRODUCTS = [
  {
    sku: "na-dash-bulb-kit",
    title: "NA Dash Bulb Refresh Kit",
    price: "18.00",
    category: "Lighting",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5, Eunos Roadster and Miata cluster illumination",
    image: "./img/p3.jpg",
    badge: "Tested on 1994 NA",
    rating: "(32)",
    difficulty: "Easy",
    time: "25-40 min",
    tools: "Phillips screwdriver, trim tool",
    included: "Matched dash bulbs, fitment notes, QR install guide",
    description:
      "Dash bulbs and fitment notes for tired NA cluster illumination.",
    qc: "Bench checked before packing and test fitted against an NA cluster.",
  },
  {
    sku: "na-interior-led-kit",
    title: "NA Interior LED Kit",
    price: "14.00",
    category: "Lighting",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5 cabin, boot and number plate positions",
    image: "./img/category-interior-product-placeholder.jpg",
    badge: "Launch range",
    rating: "(18)",
    difficulty: "Easy",
    time: "10-20 min",
    tools: "Small flat trim tool",
    included: "Interior LEDs, polarity note, QR install guide",
    description:
      "Interior LEDs selected for usable brightness and clean fitment.",
    qc: "Checked for polarity, fit and sensible colour temperature.",
  },
  {
    sku: "na-cup-holder",
    title: "NA 3D Printed Cup Holder",
    price: "26.00",
    category: "Interior",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5 centre console",
    image: "./img/category-3d-printed-parts-placeholder.jpg",
    badge: "Owner tested",
    rating: "(24)",
    difficulty: "No tools",
    time: "Under 5 min",
    tools: "None",
    included: "Printed cup holder, care note",
    description:
      "Removable NA cup holder designed around real-world cabin use.",
    qc: "Printed in small batches and checked for surface finish and console fit.",
  },
  {
    sku: "na-switch-blank-pair",
    title: "NA Switch Blank Pair",
    price: "9.00",
    category: "Trim",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5 dashboard switch openings",
    image: "./img/category-switch-blanks-product-placeholder.jpg",
    badge: "Small batch",
    rating: "(11)",
    difficulty: "Easy",
    time: "5-10 min",
    tools: "Trim tool optional",
    included: "Two switch blanks, fitment card",
    description:
      "Replacement switch blanks for tidying worn or missing dash slots.",
    qc: "Each pair is checked for clip shape and visible finish.",
  },
  {
    sku: "na-gauge-holder-52mm",
    title: "NA 52mm Gauge Holder",
    price: "22.00",
    category: "Interior",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5, universal 52mm gauge body",
    image: "./img/category-gauge-holders-product-placeholder.jpg",
    badge: "Turbo build useful",
    rating: "(15)",
    difficulty: "Moderate",
    time: "30-60 min",
    tools: "Trim tool, drill depending on route",
    included: "Gauge holder, fitting note, QR install guide",
    description:
      "Simple 52mm mounting solution for boost, oil pressure, and more.",
    qc: "Tested with common 52mm gauges and checked against an NA interior.",
  },
  {
    sku: "na-owner-bundle",
    title: "NA First Fix Bundle",
    price: "39.00",
    category: "Bundles",
    model: "NA",
    years: "1989-1997",
    fitment: "Mk1 / NA MX-5 starter refresh bundle",
    image: "./img/category-owner-bundle-flatlay-placeholder.jpg",
    badge: "Best value",
    rating: "(27)",
    difficulty: "Easy",
    time: "45-75 min",
    tools: "Basic trim tools",
    included: "Dash bulb kit, interior LED kit, switch blank pair",
    description:
      "Grouped upgrades for new owners, interior refreshes, and common fixes.",
    qc: "Bundled from the same checked parts used in individual kits.",
  },
];
